name: tumbler
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  animator:
  auto_size_text: ^3.0.0
  carousel_slider: ^4.0.0
  chewie:
  cupertino_icons: ^1.0.2
  dartdoc: ^4.1.0
  flutter_colorpicker: ^1.0.3
  flutter_dotenv: ^5.0.2
  fluttertoast: ^8.0.8
  flutter_html: ^2.2.1
  flutter_native_splash:
  flutter_lints: ^1.0.4
  flutter_widget_from_html: ^0.8.2
  font_awesome_flutter: ^9.2.0
  gif_view: ^0.0.1
  google_fonts: ^2.1.0
  google_sign_in: ^5.2.1
  html_editor_enhanced: ^2.4.0+1
  http: ^0.13.4
  intl: ^0.17.0
  like_button: ^2.0.3
  path_provider: ^2.0.7
  provider: ^6.0.1
  sqflite: ^2.0.1
  video_player: ^2.2.7
  url_launcher: ^6.0.17
  image_picker: ^0.8.4+4
  contained_tab_bar_view: ^0.8.0
  enhanced_drop_down: ^0.1.7+1
  pusher_client: ^2.0.0
  flutter_pusher: ^1.0.3
  random_color: ^1.0.6-nullsafety
  infinite_scroll_pagination: ^3.1.0
  sliver_header_delegate: ^0.0.5
  flutter_launcher_icons: ^0.9.2
  simple_url_preview: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter_native_splash:
  color: "#001935"
  image: assets/images/logo_letter.png
  flutter_launcher_icons: "^0.9.2"
flutter_icons:
    android: "launcher_icon"
    ios: true
    image_path: "assets/images/tumbler_logo.jpg"
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true



  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/fonts/
    - .env

    - assets/images/intro_1.gif
    - assets/images/intro_2.gif
    - assets/images/intro_2.webp
    - assets/images/intro_3.jpg
    - assets/images/intro_4.jpg
    - assets/images/intro_5.gif
    - assets/images/logo.png
    - assets/images/logo_letter.png
    - assets/images/create_post.png
    - assets/images/capital_letter.png
    - assets/images/quote.png
    - assets/images/intro_2_delayed.gif
    - assets/images/create_tumblr.png
    - assets/images/cat.png
    - assets/images/express_ys.png
    - assets/images/women.png
    - assets/images/search_1.jpg
    - assets/images/search_2.jpg
    - assets/images/search_3.jpg
    - assets/images/search_4.jpg
    - assets/images/search_5.png
    - assets/images/search_6.jpg
    - assets/images/search_7.jpg
    - assets/images/search_8.jpg
    - assets/images/search_9.jpg
    - assets/images/1.png
    - assets/images/2.png
    - assets/images/3.png
    - assets/images/4.png
    - assets/images/5.png
    - assets/images/6.png
    - assets/images/7.png
    - assets/images/8.png
    - assets/images/9.png


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: HelviticaNeueMedium
      fonts:
        - asset: assets/fonts/helvetica_medium/Helvetica-Neue-Medium-Extended.ttf
    - family: HelviticaNeueLight
      fonts:
        - asset: assets/fonts/helvitica_light/Helvetica-Neue-UltraLight.ttf
    - family: favoritPro
      fonts:
        - asset: assets/fonts/favorit/FavoritPro-Regular.ttf
    - family: OpensSans
      fonts:
        - asset: assets/fonts/OpenSans/OpenSans-Regular.ttf
        - asset: assets/fonts/OpenSans/OpenSans-Bold.ttf
        - asset: assets/fonts/OpenSans/OpenSans-Light.ttf
    - family: fav
      fonts:
        - asset: assets/fonts/favorit/favorit-85-cf2f6136.woff2
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
